### ISSUE TITLE
Feature Request: A toggle mute bind (with `m`)

### ISSUE THREAD

**Issue by brian6932** [zX3no/gonk#31]
Small QoL UX thing

**Comment by zfphex** [comment]
![key layout](https://user-images.githubusercontent.com/28522740/210667994-9bfcb176-9a41-4f9b-8ecf-e78a068dc63d.png)

I've added z as toggle mute.
I'm not a huge fan of phenetic keybinds. Things like m for mute. 
Just wanted to get your thoughts on the current layout.

**Comment by brian6932** [comment]
Seems good
