### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', gonk-core\src\lazy.rs:76:34

### ISSUE THREAD

**Issue by brian6932** [zX3no/gonk#33]
```rust
stack backtrace:
   0:     0x7ff7df8cbac2 - <unknown>
   1:     0x7ff7df8e4b6b - <unknown>
   2:     0x7ff7df8c78ba - <unknown>
   3:     0x7ff7df8cb80b - <unknown>
   4:     0x7ff7df8ce44a - <unknown>
   5:     0x7ff7df8ce0b0 - <unknown>
   6:     0x7ff7df8ceb26 - <unknown>
   7:     0x7ff7df8ce9db - <unknown>
   8:     0x7ff7df8cc489 - <unknown>
   9:     0x7ff7df8ce730 - <unknown>
  10:     0x7ff7df8fec05 - <unknown>
  11:     0x7ff7df8fecbc - <unknown>
  12:     0x7ff7df791863 - <unknown>
  13:     0x7ff7df791095 - <unknown>
  14:     0x7ff7df749510 - <unknown>
  15:     0x7ff7df758cf6 - <unknown>
  16:     0x7ff7df75c19c - <unknown>
  17:     0x7ff7df8c148e - <unknown>
  18:     0x7ff7df74d80c - <unknown>
  19:     0x7ff7df8ec6d4 - <unknown>
  20:     0x7ffd41ee117e - BaseThreadInitThunk
  21:     0x7ffd424242db - RtlUserThreadStart
  ```
  Happens when using the bin, no matter the arguments
  
Installed with:
  ```fish
cargo +nightly install --git https://github.com/zX3no/gonk.git
  ```

**Comment by zfphex** [comment]
I've removed lazy loading from the virtual database, so 5d646ad54563dc48eb05d64beb8c0337e664ea93 might work for you.
Make sure to run `gonk reset` first, it probably wasn't letting reset it before because arguments were handle after the database.

If you've been using the new database in #32 it probably caused some issues for you. Hopefully when that's done there won't be issues like this.

EDIT: I don't think this will work. I'm checking another problem.

**Comment by brian6932** [comment]
I tried both building with checking out that PR, and also not, had the same issue
I would `gonk reset`, but it gives me the same error, even after rebuilding from latest head

**Comment by zfphex** [comment]
If you can't run `reset`. You can just manually delete the database. Just delete all the *.db files in `%appdata%/gonk`.

**Comment by zfphex** [comment]
Can you tell me if you get any errors with 2a8d582d361ea0580aebf70cc391398f27f14e07. Thanks!

**Comment by brian6932** [comment]
I ran 
```pwsh
rm "$env:APPDATA\gonk\*.db"
```
However I'm getting the same error, nothing gets added to `gonk.log` either
Can't run `--version` either to show the commit, I'm gonna try updating and see if it's fixed

**Comment by brian6932** [comment]
Ok updated to https://github.com/zX3no/gonk/commit/2a8d582d361ea0580aebf70cc391398f27f14e07, it's now working, took a while scanning for files.
