### ISSUE TITLE
CLI logs overlapping with TUI

### ISSUE THREAD

**Issue by brian6932** [zX3no/gonk#36]
![](https://github.com/zX3no/gonk/assets/18603393/e6973b10-6ffa-4995-b8b3-44b47d8afcd4)
Version 4cbfd31e283b17513174548d350bdba7c08254d6

**Comment by zfphex** [comment]
`cargo install --path gonk --features "strip"`

**Comment by brian6932** [comment]
`cargo install --git https://github.com/zX3no/gonk gonk --features strip` works
